Upgrading to the latest revision of Panther (10.3.9) solved this, I can now successfully use my external drive.
Thanks for input.
